name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag runtime_ub20:v1

    - uses: actions/upload-artifact@v2
    - name: Store image
      run: docker save runtime_ub20:v1 -o runtime_img.tar
      # 在 with 中定义的选项将传递给上传操作
    - with:
        name: docker-image
        path: runtime_img.tar
